### ISSUE TITLE
How do I make predictions on new image? Particularly, I want to know how to detect objects for visual relationship detection?

### ISSUE THREAD

**Issue by wenzhendeng** [deeplab-ai/matranse#1]

**Comment by nickgkan** [comment]
Hello,
You have to run an object detector on your own first, to get the bounding boxes and object class labels. Notice that if you use a pretrained detector, you'll have to transform the object vocabulary to match with VRD's.
I suggest you check out the code of ATR-Net that:
1. Offers code to train object detectors on VRD and VG.
2. Lets you use GloVe embeddings by default and thus can work with vocabularies different than VRD's as well.
